USE master;
GO
DROP DATABASE IF EXISTS ENCHERES;
GO
CREATE DATABASE ENCHERES;
GO
USE ENCHERES;
GO
CREATE USER utilisateurBDD FOR LOGIN utilisateurBDD;
GO
ALTER ROLE db_owner	ADD MEMBER utilisateurBDD;
GO